SCHEMA_USER_VERSION_BASE = 1000

STATE_SCHEMA_FAMILY = "meetily-memory-state"
INDEX_SCHEMA_FAMILY = "meetily-memory-index"

STATE_APPLICATION_ID = 0x4D4D5354
INDEX_APPLICATION_ID = 0x4D4D4958

STATE_SCHEMA_EPOCH = 2
INDEX_SCHEMA_EPOCH = 2

STATE_SCHEMA_USER_VERSION = SCHEMA_USER_VERSION_BASE + STATE_SCHEMA_EPOCH
INDEX_SCHEMA_USER_VERSION = SCHEMA_USER_VERSION_BASE + INDEX_SCHEMA_EPOCH
